# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170827_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='community',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='community', to='users.Community'),
        ),
        migrations.AlterField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_owner', to='users.Profile'),
        ),
        migrations.RemoveField(
            model_name='service',
            name='tags',
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
